name: atlas
channels:
  - defaults
  - conda-forge
dependencies:
  # Python version
  - python=3.11
  - faiss-gpu
  - numpy
  # Hugging Face libraries and pytorch
  - pip
  - pip:
      - torch==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - transformers
      - accelerate
      - pandas
      - matplotlib
      - jupyterlab
      - pre-commit==4.2.0
      - types-PyYAML==6.0.12.20250809
      - pytest==8.3.5
      - pytest-cov==6.2.0
      - sentence-transformers
